### ISSUE TITLE
Interface Segregation

### ISSUE THREAD

**Issue by smudge202** [sblackler/compose-remoting#28]
I'm often guilty of this also, but on interfaces like `ISerializationProvider`, although it makes sense to provide `Serialize` and `Deserialize` together, interface segregation principle (SOLID) says the interfaces should be split. Although it's true that all serialised messages will need deserialised, no single class would need to do both as far as I know?

**Comment by sblackler** [comment]
Hmm I dont think this is as easy to split out if im honest. If we split out the 3 main providers into 6 interfaces, we would then need a linking method to say the message was compressed with x and can be decompressed with y. I'd be interested in Matt's opinion on this given the above scenario.

**Comment by sblackler** [comment]
//cc @mattridgway

**Comment by mattridgway** [comment]
Can the compression be inferred?

**Comment by sblackler** [comment]
Whether its compression/encryption/serialization the issue is still the same. How do we infer that the action of one provider (eg the compressor) is related to the related action of a different provider (eg the decompressor). By keeping them under the same contract, I have said that these two are related and we then only have to provide a single property to deal with this stuff.

To be clear, I'm not disagreeing that the single responsibility is slightly broken here, I just don't know the best way forward. So I guess, currently at least, inference is done by message properties
